output "automq_byoc_env_id" {
  description = "This parameter is used to create resources within the environment. Additionally, all cloud resource names will incorporate this parameter as part of their names. This parameter supports only numbers, uppercase and lowercase English letters, and hyphens. It must start with a letter and is limited to a length of 32 characters."
  value = var.automq_byoc_env_id
}

output "automq_byoc_endpoint" {
  description = "The endpoint for the AutoMQ environment console. Users can set this endpoint to the AutoMQ Terraform Provider to manage resources through Terraform. Additionally, users can access this endpoint via web browser, log in, and manage resources within the environment using the WebUI."
  value = "http://${aws_eip.web_ip.public_ip}:8080"
}

output "automq_byoc_initial_username" {
  description = "The initial username for the AutoMQ environment console. It has the `EnvironmentAdmin` role permissions. This account is used to log in to the environment, create ServiceAccounts, and manage other resources. For detailed information about environment members, please refer to the [documentation](https://docs.automq.com/automq-cloud/manage-identities-and-access/member-accounts)."
  value = "admin"
}

output "automq_byoc_initial_password" {
  description = "The initial password for the AutoMQ environment console. This account is used to log in to the environment, create ServiceAccounts, and manage other resources. For detailed information about environment members, please refer to the [documentation](https://docs.automq.com/automq-cloud/manage-identities-and-access/member-accounts)."
  value = aws_instance.automq-byoc-console.id
}

output "automq_byoc_vpc_id" {
  description = "The VPC ID for the AutoMQ environment deployment."
  value = local.automq_byoc_vpc_id
}

output "automq_byoc_instance_id" {
  description = "The EC2 instance id for AutoMQ Console."
  value = aws_instance.automq-byoc-console.id
}

/*
output "automq_byoc_data_bucket_name" {
  description = "The object storage bucket for that used to store message data generated by applications. The message data Bucket must be separate from the Ops Bucket."
  value = local.automq_data_bucket
}

output "automq_byoc_ops_bucket_name" {
  description = "The object storage bucket for that used to store AutoMQ system logs and metrics data for system monitoring and alerts. This Bucket does not contain any application business data. The Ops Bucket must be separate from the message data Bucket."
  value = local.automq_ops_bucket
}

output "automq_byoc_env_console_ec2_instance_ip" {
  description = "The instance IP of the deployed AutoMQ BYOC control panel. You can access the service through this IP."
  value = aws_eip.web_ip.public_ip
}

output "automq_byoc_env_console_public_subnet_id" {
  description = "The VPC subnet for the AutoMQ environment deployment."
  value = local.automq_byoc_env_console_public_subnet_id
}

output "automq_byoc_security_group_name" {
  description = "Security group bound to the AutoMQ BYOC service."
  value = aws_security_group.automq_byoc_console_sg.name
}

output "automq_byoc_role_arn" {
  description = "AutoMQ BYOC is bound to the role arn of the Console."
  value = aws_iam_role.automq_byoc_role.arn
}

output "automq_byoc_policy_arn" {
  description = "AutoMQ BYOC is bound to a custom policy on the role arn."
  value = aws_iam_policy.automq_byoc_policy.arn
}

output "automq_byoc_instance_profile_arn" {
  description = "Instance configuration file ARN"
  value = aws_iam_instance_profile.automq_byoc_instance_profile.arn
}

output "automq_byoc_vpc_route53_zone_id" {
  description = "Route53 bound to the VPC."
  value = aws_route53_zone.private.zone_id
}

output "automq_byoc_env_console_ami" {
  description = "Mirror ami id of AutoMQ BYOC Console."
  value = var.automq_byoc_env_console_ami
}

output "automq_byoc_env_console_cidr" {
  description = "AutoMQ BYOC security group CIDR."
  value = var.automq_byoc_env_console_cidr
}
*/