# outputs.tf
output "automq_byoc_env_id" {
  description = "This parameter is used to create resources within the environment. Additionally, all cloud resource names will incorporate this parameter as part of their names. This parameter supports only numbers, uppercase and lowercase English letters, and hyphens. It must start with a letter and is limited to a length of 32 characters."
  value       = var.automq_byoc_env_id
}

output "automq_byoc_env_console_ec2_instance_ip" {
  description = "The instance IP of the deployed AutoMQ BYOC control panel. You can access the service through this IP."
  value       = aws_eip.web_ip.public_ip
}

output "automq_byoc_vpc_id" {
  description = "The VPC ID for the AutoMQ environment deployment."
  value       = var.automq_byoc_vpc_id
}

output "automq_byoc_env_console_public_subnet_id" {
  description = "The VPC subnet for the AutoMQ environment deployment."
  value       = var.automq_byoc_env_console_public_subnet_id
}

output "ebs_volume_id" {
  description = "The ID of the EBS volume attached to the web instance."
  value       = [for bd in aws_instance.web.ebs_block_device : bd.volume_id][0]
}

output "automq_byoc_security_group_name" {
  description = "Security group bound to the AutoMQ BYOC service."
  value       = aws_security_group.allow_all.name
}

output "automq_byoc_data_bucket_name" {
  description = "The object storage bucket used to store message data generated by applications. The message data Bucket must be separate from the Ops Bucket."
  value       = var.automq_byoc_data_bucket_name
}

output "automq_byoc_ops_bucket_name" {
  description = "The object storage bucket used to store AutoMQ system logs and metrics data for system monitoring and alerts. This Bucket does not contain any application business data. The Ops Bucket must be separate from the message data Bucket."
  value       = var.automq_byoc_ops_bucket_name
}

output "automq_byoc_role_arn" {
  description = "AutoMQ BYOC is bound to the role ARN of the Console."
  value       = aws_iam_role.automq_byoc_role.arn
}

output "automq_byoc_policy_arn" {
  description = "AutoMQ BYOC is bound to a custom policy on the role ARN."
  value       = aws_iam_policy.automq_byoc_policy.arn
}

output "automq_byoc_vpc_route53_zone_id" {
  description = "Route53 bound to the VPC."
  value       = aws_route53_zone.private.zone_id
}

output "automq_byoc_instance_profile_arn" {
  description = "The ARN of the instance profile for automq_byoc_service_role."
  value       = aws_iam_instance_profile.automq_byoc_instance_profile.arn
}

output "automq_byoc_endpoint" {
  value = "http://${aws_eip.web_ip.public_ip}:8080"
}

output "automq_byoc_env_console_ami" {
  value = var.specified_ami_by_marketplace ? data.aws_ami.marketplace_ami_details.id : var.automq_byoc_env_console_ami
}

output "automq_byoc_instance_id" {
  description = "AutoMQ BYOC Console instance ID."
  value = aws_instance.web.id
}

output "automq_byoc_env_console_cidr" {
  description = "AutoMQ BYOC security group CIDR"
  value = var.automq_byoc_env_console_cidr
}